// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Y__7tB_AN2fPRboAymuw4YozJ_QnsjI',
    appId: '1:507604733074:web:ac445f27da0039c6806a4b',
    messagingSenderId: '507604733074',
    projectId: 'sddp-dsh-firebase',
    authDomain: 'sddp-dsh-firebase.firebaseapp.com',
    storageBucket: 'sddp-dsh-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuB6nex1vPGg9YEIpuYb5yeSsxHIfwSug',
    appId: '1:507604733074:android:f69ede090312b0d8806a4b',
    messagingSenderId: '507604733074',
    projectId: 'sddp-dsh-firebase',
    storageBucket: 'sddp-dsh-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZMCzy96WSMUhYuhP30g1RLbDM-iK6Wi4',
    appId: '1:507604733074:ios:00cc36cf69ba261c806a4b',
    messagingSenderId: '507604733074',
    projectId: 'sddp-dsh-firebase',
    storageBucket: 'sddp-dsh-firebase.firebasestorage.app',
    iosBundleId: 'com.example.sddpDsh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZMCzy96WSMUhYuhP30g1RLbDM-iK6Wi4',
    appId: '1:507604733074:ios:00cc36cf69ba261c806a4b',
    messagingSenderId: '507604733074',
    projectId: 'sddp-dsh-firebase',
    storageBucket: 'sddp-dsh-firebase.firebasestorage.app',
    iosBundleId: 'com.example.sddpDsh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Y__7tB_AN2fPRboAymuw4YozJ_QnsjI',
    appId: '1:507604733074:web:f4ee75c1914891c4806a4b',
    messagingSenderId: '507604733074',
    projectId: 'sddp-dsh-firebase',
    authDomain: 'sddp-dsh-firebase.firebaseapp.com',
    storageBucket: 'sddp-dsh-firebase.firebasestorage.app',
  );
}
